### ISSUE TITLE
https://kanali.io/ is broken

### ISSUE THREAD

**Issue by wpbeckwith** [northwesternmutual/kanali#89]
There are a lot of missing images and I imagine css styling.

**Comment by frankgreco** [comment]
@wpbeckwith We are finalizing the docs site that is being hosted on GitHub pages. Once that is complete, the *This site is under active development* banner will be removed. This should be completed in a day or so.

Can you provide a screenshot of the missing css styling so that I can make sure it is resolved?

**Comment by frankgreco** [comment]
@wpbeckwith images have been restored. Please clear browser cache and retry.
